import type { Metadata } from "next";
// import { Geist, Geist_Mono, Teachers } from "next/font/google";
import "./globals.css";
import { Teachers } from "next/font/google";


const teachers = Teachers({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-teachers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${teachers.variable} font-teachers antialiased`}>
        {children}
      </body>
    </html>
  );
}